title: Hemin Choi # your name (or website title) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Assistant Professor
  Hallym University
  <br><br>
  Second descriptions 
  <br><br>
  <a href="https://www.linkedin.com/in/example/">View My LinkedIn Profile</a> 
logo: "/images/logo.png?raw=true" # your photo (or logo) here

  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme



       
